### ISSUE TITLE
Stacktrace on recently added video

### ISSUE THREAD

**Issue by AdUser** [SHTrassEr/TubeWarden#1]
```
TypeError: /home/shtrasser_dev/TubeWarden/bin/site/views/video.pug:10
    8|   div.media
    9|     div.media-left
  > 10|       a(href='https://www.youtube.com/watch?v=' + video.videoId )
    11|         img.card-img-left(src='https://img.youtube.com/vi/' + video.videoId + '/2.jpg')
    12|     div.media-body
    13|       h4.media-heading

Cannot read property 'videoId' of null
    at eval (eval at wrap (/home/shtrasser_dev/TubeWarden/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:119:96)
    at template (eval at wrap (/home/shtrasser_dev/TubeWarden/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:252:50)
    at Object.exports.renderFile (/home/shtrasser_dev/TubeWarden/node_modules/pug/lib/index.js:418:38)
    at Object.exports.renderFile (/home/shtrasser_dev/TubeWarden/node_modules/pug/lib/index.js:408:21)
    at View.exports.__express [as engine] (/home/shtrasser_dev/TubeWarden/node_modules/pug/lib/index.js:455:11)
    at View.render (/home/shtrasser_dev/TubeWarden/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/shtrasser_dev/TubeWarden/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/shtrasser_dev/TubeWarden/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/shtrasser_dev/TubeWarden/node_modules/express/lib/response.js:1008:7)
    at /home/shtrasser_dev/TubeWarden/bin/site/controllers/video.js:22:13
    at Generator.next (<anonymous>)
    at fulfilled (/home/shtrasser_dev/TubeWarden/bin/site/controllers/video.js:4:58)
    at <anonymous>
```

**Comment by SHTrassEr** [comment]
Fixed
